import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@app/styles/globals.css" ;
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quotation Template",
  description: "Generated by Milologic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        {children}
        </body>
    </html>
  );
}
